name: Piano server
run-name: ${{ github.actor }} is testing Piano server
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo Instalando flask...
      - name: install-Flask
        run: python3 -m pip install Flask
      - name: Iniciando servidor...
        run: python3 ./server.py
      - run: echo Se ha detenido el servidor.
