name: page
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Iniciando..."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Init server
        run: echo "Creando servidor..."
             python ${{ github.workspace }}/server.py
